### ISSUE TITLE
Is  replace_monkey_uiautomator necessary?

### ISSUE THREAD

**Issue by Tangsuuu** [DroidTest/TimeMachine#13]
I test Wordpress_349.apk on android25 emulator.
But monkey didn't work well. It start the app, and then take no action.

so I edit the replace_monkey_uiautomator :
replace_monkey_uiautomator(){
	adb -s $AVD_SERIAL root
	wait_adb
	adb -s $AVD_SERIAL remount
	#  adb -s $AVD_SERIAL push libs/monkey /system/bin/
	#   adb -s $AVD_SERIAL push libs/monkey.jar /system/framework/
		adb -s $AVD_SERIAL push libs/uiautomator.jar /system/framework/
	#  adb -s $AVD_SERIAL shell chmod 777 /system/framework/monkey.jar
	adb -s $AVD_SERIAL shell chmod 777 /system/framework/uiautomator.jar
	# adb -s $AVD_SERIAL shell chmod 777 /system/bin/monkey
}

Is this modification feasible？

**Comment by Allen1346** [comment]
TimeMachine uses a modified monkey.jar to enhance its exploration ability, so the replacement is recommended. Is there any generated testing logs provided (such as timemachine-run.log) for a more detailed check?

**Comment by Tangsuuu** [comment]
I just replace the compute_coverage and pull_coverage_jacoco with Emma command, it works well.
pull_coverage_jacoco.sh:
adb -s $AVD_SERIAL shell am broadcast -a edu.gatech.m3.emma.COLLECT_COVERAGE
adb -s $AVD_SERIAL pull /mnt/sdcard/coverage.ec $OUTPUT_DIR/ec_files/$ec_file_name

def read_coverage_jacoco():
    if not os.path.isfile(RunParameters.OUTPUT_DIR+'/coverage.xml'):
        return 0

    try:
        # see the format of coverage report generated by Jacoco in xml
        print "read_coverage_jacoco(output_file_dir_path):"
        xmldoc = minidom.parse(RunParameters.OUTPUT_DIR+'/coverage.xml')
        data = xmldoc.documentElement
        # print(data)
        # stus = data.getAttribute('data')
        # stus = data.getElementsByTagName('data')[0].getElementsByTagName('all')[0] #.getAttribute('name')
        stus = data.getElementsByTagName('coverage')
        text = stus[3].getAttribute('value')
        print(text)
        text = text.split(' ')[-1][1:-1].split('/')
        print(text)
        missed_lines = float(text[0])
        covered_lines = float(text[1])
        line_coverage = float(text[0]) / float(text[1])
        return line_coverage

In  timemachine-run.log, i find "--monkey watcher is terminated! no app info in logs ---".

timemachine-run.log:

[VALIDATE MESSAGE]
---
SUCCESS: coverage file is valid!
 
compute_coverage-return code:  output: -in /home/tangsu/timemachine_data/CountdownTimer/coverage.em
EMMA: processing input files ...
EMMA: 4 file(s) read and merged in 11 ms
EMMA: writing [xml] report to [/home/tangsu/github_project/TimeMachine/apps/CountdownTimer-debug/CountdownTimer-debug.apk.timemachine.result.emulator-5554#2022-08-08-12-21-19/coverage.xml] ...
   
read_coverage_jacoco(output_file_dir_path):
36%  (232.9/650)
[u'232.9', u'650']
--the current line coverage : 0.358307692308
INITIAL k_neighbour_fitness: key: INITIAL snapshot: True hit: 1 restore: 0 trans: 0 fitness: 100.0 old trans: 0
edges: 
--the fittest state is INITIAL
--load the fittest state...
--killing monkey
Num of restores: 1
adb -s emulator-5554 shell logcat | grep controllable_widgets
-- log monitor is on...
starting monkey...
adb -s emulator-5554 shell monkey -p net.everythingandroid.timer --ignore-crashes --ignore-timeouts --ignore-security-exceptions  --ignore-native-crashes --throttle 200 -v  999999 
 crash watcher starting...
read_coverage_jacoco(output_file_dir_path):
36%  (232.9/650)
[u'232.9', u'650']
--monkey watcher is terminated!
no app info in logs ---
get_jacoco_coverage- return code:  output: Broadcasting: Intent { act=edu.gatech.m3.emma.COLLECT_COVERAGE }
Broadcast completed: result=0
---
[COVERAGE FILE EXIST?]
Alarms
DCIM
Download
Movies
Music
Notifications
Pictures
Podcasts
Ringtones
coverage.ec
---
/mnt/sdcard/coverage.ec: 1 file pulled, 0 skipped. 45.9 MB/s (37172 bytes in 0.001s)
---
[VALIDATE COVERAGE FILE]$ java -jar /home/tangsu/github_project/TimeMachine/fuzzingandroid/libs/jacococli.jar report /home/tangsu/github_project/TimeMachine/apps/CountdownTimer-debug/CountdownTimer-debug.apk.timemachine.result.emulator-5554#2022-08-08-12-21-19/ec_files/emulator-55542022-08-08-12-21-49.ec  -in /home/tangsu/timemachine_data/CountdownTimer/coverage.em &> temp
---
---
[VALIDATE MESSAGE]
---
SUCCESS: coverage file is valid!
 adb: unknown command rm
 
compute_coverage-return code:  output: -in /home/tangsu/timemachine_data/CountdownTimer/coverage.em
EMMA: processing input files ...
EMMA: 6 file(s) read and merged in 14 ms
EMMA: writing [xml] report to [/home/tangsu/github_project/TimeMachine/apps/CountdownTimer-debug/CountdownTimer-debug.apk.timemachine.result.emulator-5554#2022-08-08-12-21-19/coverage.xml] ...
   
read_coverage_jacoco(output_file_dir_path):
38%  (246.9/650)
[u'246.9', u'650']
--the current line coverage : 0.379846153846
INITIAL k_neighbour_fitness: key: INITIAL snapshot: True hit: 1 restore: 1 trans: 0 fitness: 100.0 old trans: 0
edges: 
--the fittest state is INITIAL
--load the fittest state...
--killing monkey
Num of restores: 2
adb -s emulator-5554 shell logcat | grep controllable_widgets
-- log monitor is on...
starting monkey...
crash watcher starting...
adb -s emulator-5554 shell monkey -p net.everythingandroid.timer --ignore-crashes --ignore-timeouts --ignore-security-exceptions  --ignore-native-crashes --throttle 200 -v  999999 
read_coverage_jacoco(output_file_dir_path):
38%  (246.9/650)
[u'246.9', u'650']
--monkey watcher is terminated!
no app info in logs ---
get_jacoco_coverage- return code:  output: Broadcasting: Intent { act=edu.gatech.m3.emma.COLLECT_COVERAGE }
Broadcast completed: result=0
---
[COVERAGE FILE EXIST?]

**Comment by Allen1346** [comment]
As for the log "--monkey watcher is terminated! no app info in logs ---", when TimeMachine is loading the fittest state, it will kill the current monkey process, generating this log, and will restart monkey in next loop. Or if the monkey process is killed by other interrupts (such as keyboard input), this log will also occur.
