### ISSUE TITLE
oyente 咨询

### ISSUE THREAD

**Issue by GvcZhang** [DroidTest/TimeMachine#5]
你好，我现在遇到一个问题，不能成功运行：https://github.com/melonproject/oyente

可否提供一点帮助，非常感谢。

**Comment by yxliang01** [comment]
@GvcZhang This repo is for TimeMachine instead of Oyente. Please file an issue with concrete description at the relevant repo.

此代码仓库是TimeMachine的，而非Oyente的。你应该在Oyente仓库里面提交issue来询问关于执行的问题。

**Comment by GvcZhang** [comment]
他们那个好久都不维护了的，我现在遇到这么个问题
![image](https://user-images.githubusercontent.com/45255699/76644321-be901b80-6591-11ea-9a13-69da20ef239e.png)
应该跟Dockerfile有关，可是我也不知道怎么做才行，希望能得到你的一点帮助，感激不尽
