### ISSUE TITLE
How to get executed methods records in TimeMachine

### ISSUE THREAD

**Issue by sunxiaobiu** [DroidTest/TimeMachine#8]
I am trying to run TimeMachine for code coverage analysis. The output file of TimeMachine consists of coverage.a and cov, which only present the executed method numbers. What if I need to get the specific method signatures that have been executed ? Is it possible for Time Machine to output the method signature as well?

**Comment by zhendong2050** [comment]
Can. Ella assigns each methods an unique id. For each executed method, its is printed out at runtime. TimeMachine dynamically collects those ids and count. It may need a little of your time to investigate scripts in Timemachine and some piece of Ella.
